const imageContext = require.context("./FotoExplore", false, /\.(png|jpe?g|svg)$/);

const dataExplore=[
    //Bandung
    [{
        imgSrc: imageContext("./KawahPutih.jpg"),
        type:"Pantai",
        rating:"4.8",
        review:" (1.5k)",
        lokasi:"📍 Desa Alam Endah, Kecamatan Rancabali",
        place:"Kawah Putih",
        content:"Fasilitas: Toilet, Angkutan Ontang Anting, Mushola, Warung makan, Shelter, Dermaga Ponton, Sky walk, Sunan ibu",
        price:"Rp27.500",
    },
    {
        imgSrc: imageContext("./Cileunca.jpg"),
        type:"Danau",
        rating:"4.7",
        review:" (1.2k)",
        lokasi:"📍 Jl. Situ Cileunca, Pulosari, Kec. Pangalengan",
        place:"Situ Cileunca Pangalengan",
        content:"Fasilitas: Arung Jeram / Rafting, Paintball, Flying Fox, Offroad Landrover, Archery, Lake Tour, Fun Games ",
        price:"Rp6.000",
    },
    {
        imgSrc: imageContext("./NIMO.png"),
        type:"Attraction",
        rating:"4.5",
        review:" (1k)",
        lokasi:"📍Banjarsari, kec. Pangalengan,",
        place:"NIMO Highland",
        content:"Fasilitas: Sky bridge, Restoran Santorini, Wahana ATV ,Food court ,Mushola, Shelter, Paralayang, Paramotor, Glamping, Camping ground",
        price:"Rp25.000-35.000",
    },
    {
        imgSrc: imageContext("./Lancabali.jpg"),
        type:"Danau",
        rating:"4.6",
        review:" (1.3k)",
        lokasi:"📍 Jalan Raya Ciwidey, Patengan, Kec. Rancabali",
        place:"Glamping Lakeside Rancabali",
        content:"Fasilitas: Penginapan, Pinisi Resto, Teras Bintang ,Taman Kelinci, Taman Pakis, Food Court, Floating Lake Bridge, Perahu keliling danau, Mushola",
        price:"Rp25.000",
    }],

    //Bandung Barat
    [{
        imgSrc: imageContext("./Lembang.jpg"),
        type:"Floating Market",
        rating:"4.9",
        review:" (2.5k)",
        lokasi:"📍 Jalan Grand Hotel, Kec. Lembang",
        place:"Lembang Floating Market",
        content:"Fasilitas: Pasar terapung, Ruang makan & area santai, Berbagai macam wahana permainan, Panggung hiburan Pusat oleh-oleh,  Area parkir, Toilet, Tempat bermain anak",
        price:"Rp30.500",
    },
    {
        imgSrc: imageContext("./Tangkuban.jpg"),
        type:"Pengunungan",
        rating:"4.8",
        review:" (2k)",
        lokasi:"📍 Kabupaten Bandung Barat",
        place:"Tangkuban Perahu",
        content:"Fasilitas: Area parkir, Pusat oleh-oleh, Warung makan, Toilet,  Permandian air panas, Pusat informasi, Area pendakian, Area piknik, Spot foto ",
        price:"Rp20.000-30.000",
    },
    {
        imgSrc: imageContext("./Farm.jpg"),
        type:"Taman",
        rating:"4.6",
        review:" (1.6k)",
        lokasi:"📍 Gudangkahuripan, Kec. Lembang",
        place:"Farmhouse Susu Lembang",
        content:"Fasilitas: Area parkir, Bangunan gaya eropa, Peternakan mini/petting zoo, Kios makanan & minuman, Restoran, Toko souvenir, Area main anak, Kelas susu, Toilet",
        price:"Rp25.000-35.000",
    },
    {
        imgSrc: imageContext("./Dago.jpg"),
        type:"Attraction",
        rating:"4.7",
        review:" (1.1k)",
        lokasi:"📍  Mekarwangi, Jl. Dago Giri, Kec. Lembang",
        place:"Dago Dreampark",
        content:"Fasilitas: 35 wahana & spot foto, Area taman,  Kolam renang, Area parkir, Toilet",
        price:"Rp40.000",
    }],

    //Banjar
    [{
        imgSrc: imageContext("./SituMustika.png"),
        type:"Alam",
        rating:"4.7",
        review:" (1.3k)",
        lokasi:"📍 Karang panimbal, Kecamatan Purwaharja",
        place:"Situ Mustika",
        content:"Situ Mustika merupakan salah satu destinasi wisata di Banjar, dimana di Situ Mustika terdapat keindahan alam berupa sebuah situ danau terdapat pepohonan di tepi danau juga terdapat pulau kecil di tengah danau yang dihubungkan oleh jembatan kayu jembatan.",
        price:"Rp10.000",
    },
    {
        imgSrc: imageContext("./LembahPajamben.jpg"),
        type:"Alam",
        rating:"4.7",
        review:" (1k)",
        lokasi:"📍 Jln. Langkaplancar - Lakbok, Binangun, Pataruman",
        place:"Lembah Pajamben",
        content:"Lembah Pajamben ini merupakan salah satu destinasi wisata alam yang menunjukkan pemandangan kota dari atas bukit. Tidak hanya menawarkan keindahan alam, Lembah Pajamben juga menyediakan wahana permainan untuk anak-anak serta kuliner.",
        price:"Rp15.000",
    },
    {
        imgSrc: imageContext("./Alun.jpg"),
        type:"District",
        rating:"4.5",
        review:" (700)",
        lokasi:"📍 JGJR+5JC, Banjar, Kec. Purwaharja",
        place:"Alun-alun Kota Banjar",
        content:"Alun-alun ini merupakan pusat kegiatan masyarakat dan juga merupakan salah satu objek wisata yang populer di Kota Banjar. Ada banyak toko di sekitar alun-alun yang menjual berbagai makanan dan minuman yang lezat, jadi alun-alun ini bagus untuk istirahat setelah perjalanan jauh.",
        price:"Gratis",
    },
    {
        imgSrc: imageContext("./CagarBudaya.jpeg"),
        type:"Alam",
        rating:" 4.6",
        review:" (673)",
        lokasi:"📍Jl. Pulo Majeti, Kec. Purwaharja",
        place:"Cagar Budaya Pulau Majeti",
        content:"Ini adalah tempat berdirinya Kerajaan Onom, yang masih memiliki hubungan dengan Kerajaan Galuh, yang pernah menguasai Tanah Pasundan. Kerajaan ini sangat misterius, dan akhirnya runtuh tanpa ada yang tahu mengapa.",
        price:"Rp10.000",
    }],

    //Bekasi
    [{
        imgSrc: imageContext("./TamanKemang.jpg"),
        type:"Taman",
        rating:"4.8",
        review:" (3.2k)",
        lokasi:"📍 Jl. Niaga Raya Blok, Bojong Rawalumbu",
        place:"Taman Kemang Pratama",
        content:"Area taman dan ruang terbuka hijau untuk bersantai, berolahraga, atau sekadar menikmati udara segar. Selain itu, terdapat tempat pemancing dan pemandangan rusa.",
        price:"Gratis",
    },
    {
        imgSrc: imageContext("./GoWet.png"),
        type:"Wisata",
        rating:"4.7",
        review:" (2.1k)",
        lokasi:"📍 Jl. Southern Boulevard Kav. 1, Lambang Jaya",
        place:"Go! Wet",
        content:"menyajikan pengalaman wisata air yang dilengkapi pula dengan berbagai wahana seru seperti, perosotan air ataupun 5D theater.",
        price:"Rp120.000-70.000",
    },
    {
        imgSrc: imageContext("./SituGede.jpg"),
        type:"Alam",
        rating:"4.7",
        review:" (2k)",
        lokasi:"📍Jalan Kampung Bojong Menteng, Kec Rawalumbu",
        place:"Situ Gede Bekasi",
        content:"Situ Gede Bekasi merupakan destinasi wisata alam dengan pemandangan indah danau, hutan bahkan rawa yang terletak di tengah kota Bekasi.",
        price:"Rp10.000",
    },
    {
        imgSrc: imageContext("./Rainbow.jpg"),
        type:"Wisata",
        rating:"4.8",
        review:" (1.7k)",
        lokasi:"📍 Jalan Harapan Indah Boulevard, Tarumajaya",
        place:"Rainbow Garden",
        content:"Rainbow Garden telah menjadi salah satu tujuan wisata yang sangat diminati karena berbagai spot foto yang sangat Instagramable. Dengan lampu sorot berwarna-warni yang tersedia, tempat ini menjadi lebih mempesona untuk berfoto.",
        price:"Rp15.000",
    }],

    //Bogor
    [{
        imgSrc: imageContext("./TamanSafari.png"),
        type:"Taman",
        rating:"4.9",
        review:" (2.4k)",
        lokasi:"📍 Jalan Kapten Harun Kabir, Kec. Cisarua",
        place:"Taman Safari bogor",
        content:"Fasilitas: Bus Sadari, Danau buatan Sepeda airf KanoKolam renang, Kereta api mini, Taman burung, Baby zoo.",
        price:"Rp235.000-275.000",
    },
    {
        imgSrc: imageContext("./Jungle.jpg"),
        type:" Attraction",
        rating:"4.8",
        review:" (2.2k)",
        lokasi:"📍 Sentul Nirwana, Kec. Babakan Madang",
        place:"Jungle Land",
        content:"Fasilitas: 30+ wahana & atraksi, Restoran, Toko souvenir, Area parkir",
        price:"Rp155.000",
    },
    {
        imgSrc: imageContext("./GunungMas.jpg"),
        type:"Gunung",
        rating:"4.7",
        review:" (1.9k)",
        lokasi:"📍 Agrowisata Gunung Mas, Kec. Cisarua",
        place:"Agrowisata Gunung Mas",
        content:"Fasilitas: Tea bridge, Glamping, Fun off-road, Area piknik, Area kemah",
        price:"Rp15.000",
    },
    {
        imgSrc: imageContext("./Cimory.jpg"),
        type:"Wisata",
        rating:"4.6",
        review:" (1.3k)",
        lokasi:"📍 Jl. Raya Puncak, Kec. Cisarua",
        place:"Dairyland Riverside",
        content:"Fasilitas: Area parkir, Restoran, Ruang ibadah, Toilet, Playground anak, Jogging track, 3D Museum, Monster Aquarium, Cimory forest, Kios Cimory",
        price:"Rp25.000",
    }],

    //Ciamis
    [{
        imgSrc: imageContext("./Ciung.jpg"),
        type:"Alam",
        rating:"4.8",
        review:" (1.2k)",
        lokasi:"📍 Jl. Ciamis, Kec. Cijeungjing",
        place:"Wisata Alam Ciung Wanara",
        content:"Fasilitas: Area parkir, Area pemandian/kolam,  Area piknik, Jalur pendakian, Toilet, Area camping, Tempat penginapan, Warung atau kios",
        price:"Rp7.500",
    },
    {
        imgSrc: imageContext("./AlunCiamis.jpg"),
        type:"Wisata",
        rating:"4.8",
        review:" (1.1k)",
        lokasi:"📍 Ciamis, Kabupaten Ciamis",
        place:"Alun-Alun Ciamis Wetan",
        content:"Fasilitas: Area parkir, Taman, Tempat bermain anak, Area kuliner, Toilet ",
        price:"Gratis",
    },
    {
        imgSrc: imageContext("./Kuliner.jpg"),
        type:"Wisata Kuliner",
        rating:"4.7",
        review:" (900)",
        lokasi:"📍 Situmandala, Rancah",
        place:"Warung Kuliner Puncak Bangku",
        content:"Fasilitas: Area parkir, Toilet, Gazebo Warung-warung, kuliner Spot, selfie",
        price:"Gratis",
    },
    {
        imgSrc: imageContext("./SituLengkong.jpg"),
        type:"Alam",
        rating:"4.7",
        review:" (1.1k)",
        lokasi:"📍 Panjalu, Kabupaten Ciamis",
        place:"Situ Lengkong Panjalu",
        content:"Fasilitas: Area parkir, Toilet, Mushola, Gazebo, Perahu & kayak, Kios makanan & cenderamata",
        price:"Rp8.000",
    }],

    //Cianjur
    [{
        imgSrc: imageContext("./Nusantara.jpeg"),
        type:"Taman",
        rating:" 4.8",
        review:" (2.1k)",
        lokasi:"📍 Jl. Mariwati, Kawungluwuk, Kec. Sukaresmi",
        place:"Taman Bunga Nusantara",
        content:"Fasilitas: 23 hektar taman bunga, Taman bermain anak, Villa, Restoran",
        price:"Rp50.000",
    },
    {
        imgSrc: imageContext("./KotaBunga.jpg"),
        type:"Taman",
        rating:"4.8",
        review:" (2k)",
        lokasi:"📍 Batulawang, Cipanas,",
        place:"Little Venice Kota Bunga",
        content:"Fasilitas: Perahu, Waterpark, Resto & kafe, Area bermain anak, Toko oleh-oleh, Area parkir, Taman",
        price:"Rp30.000",
    },
    {
        imgSrc: imageContext("./Gede.jpg"),
        type:"Taman",
        rating:"4.6",
        review:" (1.6k)",
        lokasi:"📍 Pamoyanan c, Pamoyanan, Kec. Cianjur",
        place:"Mount Gede Pangrango",
        content:"Fasilitas: Taman, Area bermain anak, Area parkir, Toilet",
        price:"Rp. 29.000",
    },
    {
        imgSrc: imageContext("./JayantiBeach.jpeg"),
        type:"Pantai",
        rating:"4.6",
        review:" (1.8k)",
        lokasi:"📍 Jl. Pantai Jayanti, Cidamar, Kec. Cidaun",
        place:"Jayanti Beach",
        content:"Fasilitas: Area parkir, Toilet, Saung, Penginapan, Warung makan",
        price:"Rp5000",
    }],

    //Cimahi
    [{
        imgSrc: imageContext("./GunungBohong.jpg"),
        type:"Gunung",
        rating:"4.7",
        review:" (2.8k)",
        lokasi:"📍 Cimahi, Jawa Barat",
        place:"Gunung Bohong",
        content:"Fasilitas: Tempat parkir, Warung, Toilet",
        price:" gratis",
    },
    {
        imgSrc: imageContext("./WisataCimahii.jpg"),
        type:"Alam",
        rating:"4.8",
        review:" (2.5k)",
        lokasi:"📍Jl. Gatot Subroto, Kec. Cimahi Tengah",
        place:"Alam Wisata Cimahi",
        content:"Fasilitas: Outbond, ATV riding, Jembatan gantung, Flying fox, Berkuda atau delman, Menangkap ikan di kolam lumpur, Taman bermain anak-anak",
        price:"gratis",
    },
    {
        imgSrc: imageContext("./KolamRenangi.jpg"),
        type:"Wisata",
        rating:"4.6",
        review:" (1.5k)",
        lokasi:" 📍Jl. Ciawitali, Citeureup, Kec. Cimahi Utara",
        place:"Kolam Renang Ciawitali",
        content:"Fasilitas: Kolam anak, Kolam balita, Kolam arus, Kolam air hangat, Kolam terapi ikan, Playground, Foodcourt", 
        price:"Rp35.000-25.000",
    },
    {
        imgSrc: imageContext("./Teras.jpg"),
        type:"Wisata",
        rating:"4.8",
        review:" (1.3k)",
        lokasi:"📍 Pancanaka Hill, Jalan Sanghyang, Cihami sel",
        place:"Teras Ciseupan",
        content:"Fasilitas: Tenda camping, Api unggun, Cafe & resto",
        price:"Rp5.000",
    }],

    //Cirebon
    [{
        imgSrc: imageContext("./BanyuPanas.jpeg"),
        type:"Pemandian",
        rating:"4.8",
        review:" (3.2k)",
        lokasi:"📍Jalan Raya, Palimanan Bar., Kec. Palimanan",
        place:"Banyu Panas Gempol",
        content:"Banyak pengunjung datang ke tempat ini untuk melakukan terapi kesehatan dan mengobati berbagai penyakit. Karena banyak sumber mata air panas yang keluar langsung dari perut bumi membentuk air dan belerang di Banyu Panas Gempol.",
        price:"Rp20.000-15.000",
    },
    {
        imgSrc: imageContext("./SituSedong.jpeg"),
        type:"Alam",
        rating:"4.7",
        review:" (2.1k)",
        lokasi:"📍 Desa Sedong Lor, Kecamatan Sedong",
        place:"Situ Sedong",
        content:"Danau ini dikelilingi oleh dataran luas yang menawarkan pemandangan alam yang memesona. Salah satu daya tarik utama Situ Sedong adalah penampakan Gunung Ciremai yang megah di salah satu sudut cakrawala.",
        price:"Rp3.000",
    },
    {
        imgSrc: imageContext("./PantaiKejawanan.png"),
        type:"Pantai",
        rating:"4.6",
        review:" (1.6k)",
        lokasi:"📍 Pelabuhan Perikanan Nusantara, Pegambiran",
        place:"Pantai Kejawanan",
        content:"Pantai ini memiliki air laut yang jernih dan pasir putih yang lembut. Pengunjung dapat menikmati keindahan pantai sambil berjemur di tepi pantai, bermain air, atau makan makanan laut segar di restoran pinggir pantai.",
        price:"Rp5.500",
    },
    {
        imgSrc: imageContext("./BatuLawang.jpg"),
        type:"Pengunungan",
        rating:"4.7",
        review:" (1.5k)",
        lokasi:"📍Cupang, Kecamatan Gempol",
        place:"Batu Lawang",
        content:"Batu Lawang memiliki pemandangan alam yang memesona dengan tebing-tebing tinggi yang memagari sungai Cisanggarung. Pengunjung dapat menikmati keindahan alam dan menikmati hawa dingin.",
        price:"Rp10.000",
    }],

    //Depok
    [{
        imgSrc: imageContext("./AlunDepok.jpg"),
        type:"Public",
        rating:" 4.6",
        review:" (1.3k)",
        lokasi:"📍 Boulevard Grand Depok City, Cilodong",
        place:"Alun-alun Kota Depok",
        content:"Alun Alun Depok merupakan tempat rekreasi gratis dan area umum di Kota Depok yang bisa dinikmati oleh semua kalangan, mulai dari anak-anak, remaja, hingga dewasa.",
        price:"Gratis",
    },
    {
        imgSrc: imageContext("./SituCilodong.jpg"),
        type:"Danau",
        rating:" 4.7",
        review:" (2.1k)",
        lokasi:"📍Jl. Abdul Ghani, Kalibaru, Cilodong",
        place:"Situ Cilodong",
        content:"Situ Cilodong adalah destinasi wisata danau yang ideal untuk refreshing, menawarkan panorama alam yang memukau yang menarik banyak pengunjung",
        price:"Gratis",
    },
    {
        imgSrc: imageContext("./TamanLembah.jpeg"),
        type:"Taman",
        rating:"4.8",
        review:" (1k)",
        lokasi:"📍 Jl. Bangau Raya, Depok Jaya, Pancoran Mas",
        place:"Taman Lembah Mawar",
        content:"Taman Lembah mawar, yang terletak di Kota Depok yang  dikelilingi oleh berbagai pepohonan dan tanaman bunga yang berwarna-warni. taman ini dilengkapi dengan fasilitas seperti area bermain anak-anak, jalur jogging, ruang bermain anak, danau buatan, tempat ibadah, serta area parkir yang memadai.",
        price:"Gratis",
    },
    {
        imgSrc: imageContext("./AmazingFarm.jpg"),
        type:"Wisata",
        rating:"4.7",
        review:" (839)",
        lokasi:"📍Jl. Penarikan, Pasir Putih, Kec. Sawangan",
        place:"D'Kandang Amazing Farm",
        content:"D'Kandang Amazing Farm adalah wisata peternakan di Depok, Jawa Barat, Indonesia. Pengalaman berpeternakan yang interaktif dan edukatif disediakan untuk pengunjung, terutama anak-anak.",
        price:"Rp25.000-50.000",
    }],

    //Garut
    [{
        imgSrc: imageContext("./KampungSampireun.jpg"),
        type:"Staycation",
        rating:"4.9",
        review:" (3.2k)",
        lokasi:"📍Jl. Raya Kamojang, Sukakarya, Samarang",
        place:"Kampung Sampireun Resort & Spa",
        content:"Terletak 1000 meter di atas permukaan laut, akomodasi ini menawarkan kerajinan, makanan lokal asli dan berbagai jenis bungalow mewah. Resor ini hanya berjarak dua jam berkendara dari Bandung dan menawarkan pemandangan indah dari pegunungan",
        price:"Rp700.000",
    },
    {
        imgSrc: imageContext("./Ranca.jpeg"),
        type:"Pantai",
        rating:" 4.7",
        review:" (2.7k)",
        lokasi:"📍 Desa Purbayani, Kecamatan Caringin",
        place:"Pantai Rancabuaya",
        content:"Pantai ini memiliki pasir yang bersih dengan suasana pemandangan yang indah. Pantai ini populer dengan spot fotonya, jadi cocok untuk pengunjung yang ingin menikmati waktu liburannya untuk bersantai dan berburu foto untuk diupload di sosial media.",
        price:"Gratis",
    },
    {
        imgSrc: imageContext("./GunungPapandayan.jpeg"),
        type:"Gunung",
        rating:"4.7",
        review:" (2.1k)",
        lokasi:"📍 Sirnajaya, Cisurupan, Garu",
        place:"Papandayan Resort and Leisure Park",
        content:"resort memiliki pemandangan alam menakjubkan dan banyak fasilitas rekreasi, seperti kolam renang, lapangan tenis, dan area bermain anak-anak. Orang-orang dapat menikmati keindahan alam dengan berbagai kegiatan, seperti bersepeda, hiking, atau sekadar bersantai di udara segar pegunungan.",
        price:"Rp10.000",
    },
    {
        imgSrc: imageContext("./Leuwi.jpeg"),
        type:"Wisata",
        rating:" 4.8",
        review:" (1.7k)",
        lokasi:"📍 Kampung Rupit, Bojong, Bungbulang",
        place:"Leuwi Jurig",
        content:"Tempat rekreasi Leuwi Jurig di Garut terkenal dengan air terjunnya yang memukau. Menikmati keindahan alam sambil berjalan-jalan di jalur hiking, berenang di kolam alami di bawah air terjun, atau melakukan kegiatan camping dan piknik adalah beberapa pilihan yang tersedia bagi pengunjung.",
        price:"Gratis",
    }],

    // //Indramayu
    // [{
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas:",
    //     price:" ",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:" ",
    //     content:"Fasilitas: ",
    //     price:" ",
    // }],

    // //Karawang
    // [{
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas:",
    //     price:" ",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:" ",
    //     content:"Fasilitas: ",
    //     price:" ",
    // }],

    // //Kuningan
    // [{
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas:",
    //     price:" ",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:" ",
    //     content:"Fasilitas: ",
    //     price:" ",
    // }],

    // //Majalengka
    // [{
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas:",
    //     price:" ",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:" ",
    //     content:"Fasilitas: ",
    //     price:" ",
    // }],


    // //Pangandaran
    // [{
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas:",
    //     price:" ",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:" ",
    //     content:"Fasilitas: ",
    //     price:" ",
    // }],


    // //Purwakarta
    // [{
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas:",
    //     price:" ",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:" ",
    //     content:"Fasilitas: ",
    //     price:" ",
    // }],

    // //Purwakarta
    // [{
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas:",
    //     price:" ",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:" ",
    //     content:"Fasilitas: ",
    //     price:" ",
    // }],

    // //Subang
    // [{
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas:",
    //     price:" ",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:" ",
    //     content:"Fasilitas: ",
    //     price:" ",
    // }],

    // //Suka Bumi
    // [{
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas:",
    //     price:" ",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:" ",
    //     content:"Fasilitas: ",
    //     price:" ",
    // }],

    // //Sumedang
    // [{
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas:",
    //     price:" ",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:" ",
    //     content:"Fasilitas: ",
    //     price:" ",
    // }],


    // //Tasikmalaya
    // [{
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas: ",
    //     price:"",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:"",
    //     content:"Fasilitas:",
    //     price:" ",
    // },
    // {
    //     imgSrc: imageContext(""),
    //     type:"",
    //     rating:"",
    //     review:" ",
    //     lokasi:" ",
    //     place:" ",
    //     content:"Fasilitas: ",
    //     price:" ",
    // }],

]

export default dataExplore;