const imageContext = require.context(
  "./images/FotoCard",
  false,
  /\.(png|jpe?g|svg)$/
);

const contents = [
  {
    title: "Suka Bumi",
    content:
      "Kota Sukabumi, juga dikenal dengan sebutan Gunahuyi dalam bahasa lokalnya, adalah destinasi menarik di provinsi Jawa Barat, Indonesia. Kota ini memiliki daya tarik tersendiri bagi wisatawan yang mencari pengalaman yang autentik dan memikat di Jawa Barat.",
    imageSrc: imageContext("./JembatanGantung.jpeg"),
    link: "SukaBumi.html",

    buttonText: "Read More",
  },
  {
    title: "Bogor",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Depok",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Bekasi",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Karawang",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Purwakarta",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Cianjur",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Bandung Barat",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Cimahi",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Kota Bandung",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Bandung",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Subang",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Indramayu",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Sumedang",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Garut",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Tasikmalaya",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Pangandaran",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Banjar",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Ciamis",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Kuningan",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Cirebon",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
  {
    title: "Majalengka",
    content: "",
    imageSrc: "",
    link: "",
    buttonText: "Read More",
  },
];

export default contents;
