const Data = [
  {
    id: 1,
    link: "bogor.html",
    img: "",
    alt: "Bogor",
    title: "Bogor",
    subtitle: "",
  },
  {
    id: 2,
    link: "depok.html",
    img: "",
    alt: "Depok",
    title: "Depok",
    subtitle: "",
  },
  {
    id: 3,
    link: "bekasi.html",
    img: "",
    alt: "Bekasi",
    title: "Bekasi",
    subtitle: "",
  },
  {
    id: 4,
    link: "karawang.html",
    img: "",
    alt: "Karawang",
    title: "Karawang",
    subtitle: "",
  },
  {
    id: 5,
    link: "purwakarta.html",
    img: "",
    alt: "Purwakarta",
    title: "Purwakarta",
    subtitle: "",
  },
  {
    id: 6,
    link: "subang.html",
    img: "",
    alt: "Subang",
    title: "Subang",
    subtitle: "",
  },
  {
    id: 7,
    link: "indramayu.html",
    img: "",
    alt: "Indramayu",
    title: "Indramayu",
    subtitle: "",
  },
  {
    id: 8,
    link: "sumedang.html",
    img: "",
    alt: "Sumedang",
    title: "Sumedang",
    subtitle: "",
  },
  {
    id: 9,
    link: "majalengka.html",
    img: "",
    alt: "Majalengka",
    title: "Majalengka",
    subtitle: "",
  },
  {
    id: 10,
    link: "cirebon.html",
    img: "",
    alt: "Cirebon",
    title: "Cirebon",
    subtitle: "",
  },
  {
    id: 11,
    link: "kuningan.html",
    img: "",
    alt: "Kuningan",
    title: "Kuningan",
    subtitle: "",
  },
  {
    id: 12,
    link: "sukabumi.html",
    img: "",
    alt: "Sukabumi",
    title: "Sukabumi",
    subtitle: "",
  },
  {
    id: 13,
    link: "cianjur.html",
    img: "",
    alt: "Cianjur",
    title: "Cianjur",
    subtitle: "",
  },
  {
    id: 14,
    link: "bandungbarat.html",
    img: "",
    alt: "Bandung Barat",
    title: "Bandung Barat",
    subtitle: "",
  },
  {
    id: 15,
    link: "cimahi.html",
    img: "",
    alt: "Cimahi",
    title: "Cimahi",
    subtitle: "",
  },
  {
    id: 16,
    link: "kotabandung.html",
    img: "",
    alt: "Kota Bandung",
    title: "Kota Bandung",
    subtitle: "",
  },
  {
    id: 17,
    link: "bandung.html",
    img: "src/component/images/kabupaten/bandung.webp",
    alt: "Bandung",
    title: "Bandung",
    subtitle: "Bandung adalah salah satu kota di Jawa Barat",
  },
  {
    id: 18,
    link: "garut.html",
    img: "",
    alt: "Garut",
    title: "Garut",
    subtitle: "",
  },
  {
    id: 19,
    link: "tasikmalaya.html",
    img: "",
    alt: "Tasikmalaya",
    title: "Tasikmalaya",
    subtitle: "",
  },
  {
    id: 20,
    link: "pangandaran.html",
    img: "",
    alt: "Pangandaran",
    title: "Pangandaran",
    subtitle: "",
  },
  {
    id: 21,
    link: "banjar.html",
    img: "",
    alt: "Banjar",
    title: "Banjar",
    subtitle: "",
  },
  {
    id: 22,
    link: "ciames.html",
    img: "",
    alt: "Ciames",
    title: "Ciames",
    subtitle: "",
  },
];
export default Data;
