const Data = [
  {
    id: 1,
    title: "Bandung",
    logo: "/images/Logokabupaten/bandungLogo.png",
    alt: "Bandung",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/bandungLink",
  },
  {
    id: 2,
    title: "Bandung Barat",
    logo: "/images/Logokabupaten/bandungbaratLogo.png",
    alt: "Bandung Barat",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/bandungbaratLink",
  },
  {
    id: 3,
    title: "Banjar",
    logo: "/images/Logokabupaten/banjarLogo.png",
    alt: "Banjar",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/",
  },
  {
    id: 4,
    title: "Bekasi",
    logo: "/images/Logokabupaten/bekasiLogo.png",
    alt: "Bekasi",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/bekasiLink",
  },
  {
    id: 5,
    title: "Bogor",
    logo: "/images/Logokabupaten/bogorLogo.png",
    alt: "Bogor",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/bogorLink",
  },
  {
    id: 6,
    title: "Ciamis",
    logo: "/images/Logokabupaten/ciamisLogo.png",
    alt: "Ciamis",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/ciamisLink",
  },
  {
    id: 7,
    title: "Cianjur",
    logo: "/images/Logokabupaten/cianjurLogo.png",
    alt: "Cianjur",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/cianjurLink",
  },
  {
    id: 8,
    title: "Cimahi",
    logo: "/images/Logokabupaten/cimahiLogo.png",
    alt: "Cimahi",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/",
  },
  {
    id: 9,
    title: "Cirebon",
    logo: "/images/Logokabupaten/cirebonLogo.png",
    alt: "Cirebon",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/cirebonLink",
  },
  {
    id: 10,
    title: "Depok",
    logo: "/images/Logokabupaten/depokLogo.png",
    alt: "Depok",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/",
  },
  {
    id: 11,
    title: "Garut",
    logo: "/images/Logokabupaten/garutLogo.png",
    alt: "Garut",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/garutLink",
  },
  {
    id: 12,
    title: "Indramayu",
    logo: "/images/Logokabupaten/indramayuLogo.png",
    alt: "Indramayu",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/indramayuLink",
  },
  {
    id: 13,
    title: "Karawang",
    logo: "/images/Logokabupaten/karawangLogo.png",
    alt: "Karawang",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/karawangLink",
  },
  {
    id: 14,
    title: "Kuningan",
    logo: "/images/Logokabupaten/kuninganLogo.png",
    alt: "Kuningan",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/kuninganLink",
  },
  {
    id: 15,
    title: "Majalengka",
    logo: "/images/Logokabupaten/majalengkaLogo.png",
    alt: "Majalengka",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/majalengkaLink",
  },
  {
    id: 16,
    title: "Pangandaran",
    logo: "/images/Logokabupaten/pangandaranLogo.png",
    alt: "Pangandaran",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/pangandaranLink",
  },
  {
    id: 17,
    title: "Purwakarta",
    logo: "/images/Logokabupaten/purwakartaLogo.png",
    alt: "Purwakarta",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/purwakartaLink",
  },
  {
    id: 18,
    title: "Subang",
    logo: "/images/Logokabupaten/subangLogo.png",
    alt: "Subang",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/subangLink",
  },
  {
    id: 19,
    title: "Suka Bumi",
    logo: "/images/Logokabupaten/sukabumiLogo.png",
    alt: "Suka Bumi",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/sukabumiLink",
  },
  {
    id: 20,
    title: "Sumedang",
    logo: "/images/Logokabupaten/sumedangLogo.png",
    alt: "Sumedang",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/sumedangLink",
  },
  {
    id: 21,
    title: "Tasikmalaya",
    logo: "/images/Logokabupaten/tasikmalayaLogo.png",
    alt: "Tasikmalaya",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/taksimalayaLink",
  },

  {
    id: 22,
    title: "Jawa Barat",
    logo: "/images/Logokabupaten/jawabaratLogo.png",
    alt: "Jawa Barat",
    shortDesc: "asdaf asdfsad asdasf asdasf asfdasf",
    link: "/",
  },
];

export default Data;
